'use client';

import "@stoplight/elements/styles.min.css";
import dynamic from "next/dynamic";
// import {

// const APIDocumentUI = dynamic<{
//   apiDescriptionUrl: string;
//   layout?: "sidebar" | "stacked";
//   router?: "history" | "memory" | "hash" | "static";
// }>(
//   import("@stoplight/elements").then(({ API }) => API),
//   {
//     ssr: false,
//     loading: () => <p>Loading...</p>,
//   }
// );

const APIDocumentUI = dynamic(
  () => import("@stoplight/elements").then(({ API }) => API),
  {
    ssr: false,
    loading: () => <div>Loading...</div>,
  }
);

// const theme = {
//   ...defaultTheme,
//   // Customize your theme here
//   colors: {
//     text: '#000',
//     background: '#fff',
//     primary: '#07c',
//     modes: {
//       dark: {
//         text: '#fff',
//         background: '#000',
//         primary: '#0cf',
//       },
//     },
//   },
// };

export default function Playground() {
  return (
    // <ThemeProvider theme={theme}>
    //   <x.div h="100vh" mx="auto">
    //     <Preflight />
    //     <Head>
    //       <title>Next Swagger Doc Demo App</title>
    //       <meta name="description" content="Generated by create next app" />
    //       <link rel="icon" href="/favicon.ico" />
    //     </Head>
    //     <APIDocumentUI
    //       apiDescriptionUrl="/swagger.json"
    //       layout="sidebar"
    //       router="hash"
    //     />
    //   </x.div>
    // </ThemeProvider>
    <div className="App h-screen">
      <APIDocumentUI apiDescriptionUrl="/swagger.json" router="hash" />
    </div>
  );
}
